# Generated by Django 3.2 on 2021-08-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210814_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tecno'), ('I', 'Itel'), ('In', 'Infinix'), ('Sm', 'Samsung'), ('Ip', 'Iphone'), ('H', 'Huwaei')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('W', 'warning'), ('I', 'info'), ('D', 'dark')], default='', max_length=1),
        ),
    ]
