# Generated by Django 3.2 on 2021-08-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210815_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('D', 'danger'), ('S', 'Secondary'), ('W', 'warning'), ('I', 'info'), ('D', 'dark')], default='', max_length=1),
        ),
    ]
