# Generated by Django 3.2 on 2021-09-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category']},
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tecno'), ('I', 'Itel'), ('In', 'Infinix'), ('Sm', 'Samsung'), ('Ip', 'Iphone'), ('H', 'Huwaei'), ('F', 'Fero'), ('O', 'Oppo')], default='', max_length=2),
        ),
    ]
